---
- name: Clusters_Info playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: 192.168.39.45
      nutanix_username: "admin"
      nutanix_password: "P@ssw0rd1234"
      validate_certs: false
  tasks:
    
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "web-server-01",
            "memory_mb": 8192,
            "num_vcpus": 4,
            "num_cores_per_vcpu": 2,
            "vm_nics": [
              {
                "network_uuid": "e1530106-3d95-4d13-a232-37d447d8f0ed",
                "is_connected": true,
                "request_ip": true
              }
            ],
            "vm_disks": [
              {
                "vm_disk_create": {
                  "size": 10240,
                  "storage_container_uuid": "47d5155f-ebe6-4fbc-b2e3-1dc44222856a"
                }
              }
            ]
          }
        body_format: json
        validate_certs: no
        return_content: yes  

      register: response  

    - name: Show API Response
      debug:
        var: response
