###### VM OPERATIONS ########
---
- name: VM operations playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: 192.168.39.45
      nutanix_username: admin
      nutanix_password: P@ssw0rd1234
      validate_certs: false
  tasks:
  - name: Setting Variables
    set_fact:
        script_path: ""
        subnet_name: ""
        vm_uuid: ""

  - name: hard power off the vm
    ntnx_vms:
        state: hard_poweroff
        vm_uuid: "{{ vm_uuid }}"
    register: result
    ignore_errors: true

  - name: create_ova_image  while vm is on
    ntnx_vms_ova:
        state: present
        src_vm_uuid: "{{ vm_uuid }}"
        name: integration_test_VMDK_ova
        file_format: VMDK
        wait: true
    register: result
    ignore_errors: true

  - name: clone vm while it's off also add network and script
    ntnx_vms_clone:
        state: present
        src_vm_uuid: "{{ vm_uuid }}"
        networks:
          - is_connected: true
            subnet:
              name: "{{ subnet_name }}"
        guest_customization:
          type: "cloud_init"
          script_path: "{{ script_path }}"
          is_overridable: True
    register: result
    ignore_errors: true
